name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ansible-community/ansible-lint-action@v6.5.2
        with:
          path: "."

  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: gofrolist/molecule-action@v2.2.41
        env:
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
