name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ansible-community/ansible-lint-action@v6.5.2
        with:
          path: "."

  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: gofrolist/molecule-action@v2.3.0
        env:
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
